// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
const { model, Schema } = require('mongoose');

const schema = new Schema({
  text: { type: String, required: true },
  image: { type: String, required: true },
  type: { type: String, required: true },
})

module.exports = model('banner', schema);
